tasks:
  - before: >
      wget -qOdatabase-setup.sh https://codejudge-starter-repo-artifacts.s3.ap-south-1.amazonaws.com/backend-project/gitpod/python/2.7/db-gitpod-setup.sh &&
      chmod 0755 database-setup.sh &&
      bash database-setup.sh
    init: |
      pip install --upgrade pip
      python -m pip install Flask==1.1.1
      pip install -r requirements.txt
    command: python restapi.py
ports:
  - port: 8080
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-python.python
